# Generated by Django 3.1.5 on 2021-02-02 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cancelledorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='relationship',
        ),
        migrations.AddField(
            model_name='order',
            name='position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='SingleProductOrder',
        ),
    ]
