# Generated by Django 3.1.5 on 2021-02-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_discarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelledorder',
            name='cancel_date',
            field=models.DateField(auto_now=True),
        ),
    ]
