# Generated by Django 3.1.5 on 2021-02-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cancelledorder_cancel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledorder',
            name='cancel_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
